import 'package:hyper_ui/core.dart';
import 'package:flutter/material.dart';

class CgMainService {
  List<Map> scaffoldList = [
    {
      'label': 'Scaffold Basic',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldSimple(),
    },
    {
      'label': 'Scaffold Bottom Navigation Bar',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldBottomNavigationBar(),
    },
    {
      'label': 'Scaffold Bottom Navigation Bar Docked',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldBottomNavigationBarDocked(),
    },
    {
      'label': 'Scaffold Bottom Navigation Bar2',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldBottomNavigationBar2(),
    },
    {
      'label': 'Scaffold Bottom Navigation Bar3',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldBottomNavigationBar3(),
    },
    {
      'label': 'Scaffold Bottom Navigation Bar4',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldBottomNavigationBar4(),
    },
    {
      'label': 'Scaffold TabBar',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldTabbarHorizontal(),
    },
    {
      'label': 'Scaffold Drawer',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldDrawer(),
    },
    {
      'label': 'Scaffold Image',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldImage(),
    },
    {
      'label': 'Scaffold SliverAppbar',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldSliverAppbar(),
    },
    {
      'label': 'Scaffold Menubar',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldMenubar(),
    },
    {
      'label': 'Scaffold SliverAppbar2',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldSliverAppbar2(),
    },
    {
      'label': 'Scaffold Floating Dialog',
      'icon': MdiIcons.devices,
      'color': Colors.blue,
      'page': const TemplateScaffoldFloatingDialog(),
    },
  ];

  List<Map> menuList = [
    {
      'label': 'HotKey',
      'icon': MdiIcons.keyboardOutline,
      'color': Colors.blue,
      'page': const CgHotkeyView(),
    },
    {
      'label': 'Common',
      'icon': MdiIcons.soccerField,
      'color': Colors.yellow,
      'page': const CgCommonView(),
    },
    {
      'label': 'Scaffold',
      'icon': MdiIcons.screwdriver,
      'color': Colors.green,
      'page': const CgScaffoldView(),
    },
    {
      'label': 'Menubar',
      'icon': MdiIcons.menu,
      'color': Colors.orange,
      'page': const CgMenubarView(),
    },
    {
      'label': 'Navigation',
      'icon': MdiIcons.mapMarkerPath,
      'color': Colors.red,
      'page': const CgNavigationView(),
    },
    {
      'label': 'Container',
      'icon': MdiIcons.card,
      'color': Colors.purple,
      'page': const CgContainerView(),
    },
    {
      'label': 'Card',
      'icon': MdiIcons.cardOutline,
      'color': Colors.purple,
      'page': const CgCardView(),
    },
    {
      'label': 'Card2',
      'icon': MdiIcons.cardOutline,
      'color': Colors.purple,
      'page': const CgCard2View(),
    },
    {
      'label': 'Card2 Statistic',
      'icon': MdiIcons.cardOutline,
      'color': Colors.purple,
      'page': const CgCard2StatisticView(),
    },
    {
      'label': 'Text',
      'icon': MdiIcons.textBox,
      'color': Colors.orange,
      'page': const CgTextView(),
    },
    {
      'label': 'Logo',
      'icon': MdiIcons.circle,
      'color': Colors.red,
      'page': const CgLogoView(),
    },
    {
      'label': 'Image',
      'icon': MdiIcons.image,
      'color': Colors.pink,
      'page': const CgImageView(),
    },
    {
      'label': 'Icon',
      'icon': MdiIcons.emoticonHappyOutline,
      'color': Colors.yellow,
      'page': const CgIconView(),
    },
    {
      'label': 'CircleAvatar',
      'icon': MdiIcons.accountCircleOutline,
      'color': Colors.teal,
      'page': const CgCircleAvatarView(),
    },
    {
      'label': 'ListView',
      'icon': MdiIcons.viewList,
      'color': Colors.indigo,
      'page': const CgListView(),
    },
    {
      'label': 'ListViewItem',
      'icon': MdiIcons.viewListOutline,
      'color': Colors.lime,
      'page': const CgListItemView(),
    },
    {
      'label': 'GridView',
      'icon': MdiIcons.viewGridPlus,
      'color': Colors.cyan,
      'page': const CgGridView(),
    },
    {
      'label': 'GridView2',
      'icon': MdiIcons.viewGridPlus,
      'color': Colors.cyan,
      'page': const CgGrid2View(),
    },
    {
      'label': 'CalendarView',
      'icon': MdiIcons.calendar,
      'color': Colors.cyan,
      'page': const CgCalendarView(),
    },
    {
      'label': 'Wrap',
      'icon': MdiIcons.wrap,
      'color': Colors.cyan,
      'page': const CgWrapView(),
    },
    {
      'label': 'TableView',
      'icon': MdiIcons.table,
      'color': Colors.cyan,
      'page': const CgTableView(),
    },
    {
      'label': 'ChartView',
      'icon': MdiIcons.chartLine,
      'color': Colors.cyan,
      'page': const CgChartView(),
    },
    {
      'label': 'MapView',
      'icon': MdiIcons.map,
      'color': Colors.cyan,
      'page': const CgMapView(),
    },
    {
      'label': 'Form',
      'icon': MdiIcons.formTextbox,
      'color': Colors.amber,
      'page': const CgFormView(),
    },
    {
      'label': 'Button',
      'icon': MdiIcons.buttonPointer,
      'color': Colors.red,
      'page': const CgButtonView(),
    },
    {
      'label': 'Carousel',
      'icon': MdiIcons.alertBoxOutline,
      'color': Colors.red,
      'page': const CgCarouselView(),
    },
    {
      'label': 'Alert',
      'icon': MdiIcons.alertBoxOutline,
      'color': Colors.grey,
      'page': const CgAlertView(),
      'tag': 'Nunggu Mood'
    },
    {
      'label': 'Get ???',
      'icon': MdiIcons.firebase,
      'color': Colors.red,
      'page': const CgGetView(),
    },
    {
      'label': 'HTTP Request',
      'icon': MdiIcons.web,
      'color': Colors.blue,
      'page': const CgHttpView(),
    },
    {
      'label': 'Firebase',
      'icon': MdiIcons.firebase,
      'color': Colors.orange,
      'page': const CgFirebaseView(),
    },
    {
      'label': 'Future',
      'icon': MdiIcons.web,
      'color': Colors.purple,
      'page': const CgFutureView(),
    },
  ];

//Buatlah List<Map> uiMenuList di Flutter yang berisi Map dengan label, icon,color dan event onPressed tanpa isi. Tambahkan 3 data di dalamnya berupa Dashboard, ListView, DetailView, ReportView, ProfileView dengan color yang unik dan gunakan MdiIcons.
  List<Map> slicingUiMenuList = [
    {
      'label': 'ELogin1',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin1View(),
    },

    {
      'label': 'ELogin2',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin2View(),
    },
    {
      'label': 'ELogin3',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin3View(),
    },
    {
      'label': 'ELogin4',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin4View(),
    },
    {
      'label': 'ELogin5',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin5View(),
    },
    {
      'label': 'ELogin6',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin6View(),
    },
    {
      'label': 'ELogin7',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin7View(),
    },
    {
      'label': 'ELogin8',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin8View(),
    },
    {
      'label': 'ELogin9',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin9View(),
    },
    {
      'label': 'ELogin10',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red[600],
      'page': const Elogin10View(),
    },
    {
      'label': 'EDashboard1',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard1View(),
    },
    {
      'label': 'EDashboard2',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard2View(),
    },
    {
      'label': 'EDashboard3',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard3View(),
    },
    {
      'label': 'EDashboard4',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard4View(),
    },
    {
      'label': 'EDashboard5',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard5View(),
    },
    {
      'label': 'EDashboard6',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard6View(),
    },
    {
      'label': 'EDashboard7',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard7View(),
    },
    {
      'label': 'EDashboard8',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard8View(),
    },
    {
      'label': 'EDashboard9',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard9View(),
    },
    {
      'label': 'EDashboard10',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const UkDashboard10View(),
    },
    {
      'label': 'EList1',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist1View(),
    },
    {
      'label': 'EList2',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist2View(),
    },
    {
      'label': 'EList3',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist3View(),
    },
    {
      'label': 'EList4',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist4View(),
    },
    {
      'label': 'EList5',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist5View(),
    },
    {
      'label': 'EList6',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist6View(),
    },
    {
      'label': 'EList7',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist7View(),
    },
    {
      'label': 'EList8',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist8View(),
    },
    {
      'label': 'EList9',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist9View(),
    },
    {
      'label': 'EList10',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Elist10View(),
    },
    {
      'label': 'Ecategory1',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory1View(),
    },
    {
      'label': 'Ecategory2',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory2View(),
    },
    {
      'label': 'Ecategory3',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory3View(),
    },
    {
      'label': 'Ecategory4',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory4View(),
    },
    {
      'label': 'Ecategory5',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory5View(),
    },
    {
      'label': 'Ecategory6',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory6View(),
    },
    {
      'label': 'Ecategory7',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory7View(),
    },
    {
      'label': 'Ecategory8',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory8View(),
    },
    {
      'label': 'Ecategory9',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory9View(),
    },
    {
      'label': 'Ecategory10',
      'icon': MdiIcons.loginVariant,
      'color': Colors.grey,
      'page': const Ecategory10View(),
    },
    // {
    //   'label': 'Login',
    //   'icon': MdiIcons.loginVariant,
    //   'color': Colors.grey,
    //   'page': CgPremadeLoginView(),
    //   'tag': 'Nunggu Mood',
    // },
    // {
    //   'label': 'Login',
    //   'icon': MdiIcons.loginVariant,
    //   'color': Colors.grey,
    //   'page': CgPremadeLoginView(),
    //   'tag': 'Nunggu Mood',
    // },
    // {
    //   'label': 'Dashboard',
    //   'icon': MdiIcons.viewDashboard,
    //   'color': Colors.grey,
    //   'page': CgPremadeDashboardView(),
    //   'tag': 'Nunggu Mood',
    // },
    // {
    //   'label': 'ListView',
    //   'icon': MdiIcons.viewList,
    //   'color': Colors.grey,
    //   'page': CgPremadeListView(),
    //   'tag': 'Nunggu Mood',
    // },
    // {
    //   'label': 'DetailView',
    //   'icon': MdiIcons.viewGrid,
    //   'color': Colors.grey,
    //   'page': CgPremadeDetailView(),
    //   'tag': 'Nunggu Mood',
    // },
    // {
    //   'label': 'ReportView',
    //   'icon': MdiIcons.chartBar,
    //   'color': Colors.grey,
    //   'page': CgPremadeReportView(),
    //   'tag': 'Nunggu Mood',
    // },
    // {
    //   'label': 'ProfileView',
    //   'icon': MdiIcons.accountCircle,
    //   'color': Colors.grey,
    //   'page': CgPremadeProfileView(),
    //   'tag': 'Nunggu Mood',
    // },
  ];

  List<Map> suiRandomList = [
    {
      'label': 'Todo Dashboard',
      'icon': MdiIcons.loginVariant,
      'color': Colors.red,
      'page': const TdDashboardView(),
    },
    {
      'label': 'Todo Dashboard',
      'icon': MdiIcons.loginVariant,
      'color': Colors.green,
      'page': const TdDashboardView(),
    },
    {
      'label': 'Todo Dashboard',
      'icon': MdiIcons.loginVariant,
      'color': Colors.blue,
      'page': const TdDashboardView(),
    },
  ];

//Buatlah List<Map> hyperUiMenuList di Fl~utter yang berisi Map dengan label, icon,color dan event onPressed tanpa isi. Tambahkan 3 data di dalamnya berupa Form, ListView, FireStream, Dialog, Navigation, Utility, MVC Generator dengan color yang unik dan gunakan MdiIcons.
  List<Map> hyperUiMenuList = [
    {
      'label': 'Button',
      'icon': MdiIcons.formTextbox,
      'color': Colors.blue,
      'page': const CgHuiButtonView(),
    },
    {
      'label': 'Form',
      'icon': MdiIcons.formTextbox,
      'color': Colors.blue,
      'page': const CgHyperuiFormView(),
    },
    {
      'label': 'ListView',
      'icon': MdiIcons.viewList,
      'color': Colors.red,
      'page': const CgHyperuiListView(),
    },
    {
      'label': 'GridView',
      'icon': MdiIcons.viewList,
      'color': Colors.green,
      'page': const CgHuiGridView(),
    },
    {
      'label': 'FireStream',
      'icon': MdiIcons.fire,
      'color': Colors.grey,
      'page': const CgHyperuiFireStreamView(),
      'tag': "Nunggu Mood",
    },
    {
      'label': 'Dialog',
      'icon': MdiIcons.message,
      'color': Colors.grey,
      'page': const CgHyperuiDialogView(),
      'tag': "Nunggu Mood",
    },
    {
      'label': 'Navigation',
      'icon': MdiIcons.navigation,
      'color': Colors.grey,
      'page': const CgHyperuiNavigationView(),
      'tag': "Nunggu Mood",
    },
    {
      'label': 'Utility',
      'icon': MdiIcons.wrench,
      'color': Colors.grey,
      'page': const CgHyperuiUtilityView(),
      'tag': "Nunggu Mood",
    },
    // {
    //   'label': 'MVC Generator',
    //   'icon': MdiIcons.codeBraces,
    //   'color': Colors.grey,
    //   'page': CgHyperuiMvcGeneratorView(),
    //   'tag': "Nunggu Mood",
    // },
  ];

//Buatlah List<Map> demoAppList di Flutter yang berisi Map dengan label, icon,color dan event onPressed tanpa isi. Tambahkan 3 data di dalamnya berupa POS, Car Rental, Barber Shop dengan color yang unik dan gunakan MdiIcons.
  List<Map> demoAppList = [
    {
      'label': 'POS',
      'icon': MdiIcons.cashRegister,
      'color': Colors.green,
      'page': Container(),
      'tag': 'Coming Soon',
    },
    {
      'label': 'Car Rental',
      'icon': MdiIcons.car,
      'color': Colors.blue,
      'page': Container(),
      'tag': 'Coming Soon',
    },
    {
      'label': 'Barber Shop',
      'icon': MdiIcons.scissorsCutting,
      'color': Colors.orange,
      'page': Container(),
      'tag': 'Coming Soon',
    },
  ];
}
